feat(01-building-blocks): adde workflow file

diff --git a/.github/workflows/01-building-blocks.yaml b/.github/workflows/01-building-blocks.yaml
--- a/.github/workflows/01-building-blocks.yaml
+++ b/.github/workflows/01-building-blocks.yaml
@@ -1,21 +1,20 @@
 name: 01 - Building Blocks
-on:
-  - push
-  - workflow_dispatch
-jobs:
-  
+
+on: workflow_dispatch
+
+jobs: 
   echo-hello:
     runs-on: ubuntu-latest
     steps:
-      - run: echo "Hello, World!"
-
-  say-goodbye:
+      - name: Say hello
+        run: echo "Hello, world!"
+  echo-goodbye:
     runs-on: ubuntu-latest
     steps:
-      - run: |
-          echo "Exiting with code 0"
-          exit 0
-        name: "Exit with code 0"
-
-      - run: echo "Goodbye!"
-        name: "Say goodbye"
+      - name: Failed step
+        run: |
+          echo "I will fail"
+          exit 1        
+      - name: Say goodbye
+        run: echo "Goodbye!"
+        
